### ISSUE TITLE
java.lang.NullPointerException

### ISSUE THREAD

**Issue by ThreaT** [amannm/SAHC4J#1]
After running Main.java and visiting https://localhost:1234 I get:

`HTTPS >> Starting TCP/IP listener on local port 1234
HTTP >> Starting TCP/IP listener on local port 8080

HTTPS /127.0.0.1:45510 << New connection
HTTPS /127.0.0.1:45510 << >> TLS handshaking...Starting handshake
Exception in thread "pool-1-thread-2" java.lang.NullPointerException
	at ontopadsimple.Main$HttpsServer.doHandshake(Main.java:146)
	at ontopadsimple.Main$HttpsServer.run(Main.java:242)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)`

**Comment by amannm** [comment]
I think I was caught in the middle of a refactor when I pushed this to GitHub. Unfortunately this was before I learned how to properly maintain code. I pushed an update that will almost fix the problem but I can't recall how I avoided the BUFFER_UNDERFLOW issue. `-Djavax.net.debug=help` and I had to understand the whole abridged vs full SSL negotiation thing...

**Comment by ThreaT** [comment]
For `BUFFER_UNDERFLOW` you have a case for `result` and you can keep repeating during `unwrap`. See: http://docs.oracle.com/javase/7/docs/api/javax/net/ssl/SSLEngineResult.Status.html#BUFFER_UNDERFLOW

**Comment by ThreaT** [comment]
The directory structure should be `src/main/java` I believe. `StandardCharsets` should not be missing.

**Comment by ThreaT** [comment]
Where can `StandardCharsets` be found? ASCII.java line 291-296

**Comment by amannm** [comment]
StandardCharsets is part of the JDK

**Comment by ThreaT** [comment]
I think you need to add:

`import java.nio.charset.StandardCharsets;`

And remove the catch for `UnsupportedEncodingException`

**Comment by ThreaT** [comment]
I've added a [pull request](https://github.com/amannm/SAHC4J/pull/2) to resolve the issue
