### ISSUE TITLE
java.nio.BufferOverflowException

### ISSUE THREAD

**Issue by ThreaT** [amannm/SAHC4J#3]
Steps to reproduce:

1. Run `Main.java`
2. Go to localhost:8080 in your browser

Output:

> HTTP >> Starting TCP/IP listener on local port 8080
> HTTPS >> Starting TCP/IP listener on local port 1234
> HTTP >> Incoming connection from /127.0.0.1:47350 ... 
> HTTP >> Request received
> HTTP >> Incoming connection from /127.0.0.1:47351 ... 
> HTTP >> Request received
> HTTP >> Incoming connection from /127.0.0.1:47352 ... 
> HTTP >> Request received
> HTTP >> Incoming connection from /127.0.0.1:47353 ... 
> HTTP >> Request received
> HTTP >> Incoming connection from /127.0.0.1:47354 ... 
> HTTP >> Request received
> HTTP >> Incoming connection from /127.0.0.1:47355 ... 
> HTTP >> Request received
> HTTP >> Incoming connection from /127.0.0.1:47356 ... 
> HTTP >> Request received
> Exception in thread "pool-1-thread-1" java.nio.BufferOverflowException
> 	at java.nio.DirectByteBuffer.put(DirectByteBuffer.java:331)
> 	at http.util.ResponseBuilder.putHTTPSRedirect(ResponseBuilder.java:38)
> 	at HttpServer.run(HttpServer.java:49)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
> 	at java.lang.Thread.run(Thread.java:745)

**Comment by ThreaT** [comment]
I believe you need to reset the application buffer size, i.e.

`appBBSize = sslEngine.getSession().getApplicationBufferSize();`
